[build]
  command = "npm run build"
  publish = ".next"

# Set runtime versions (keeps Netlify consistent with Next 14)
[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

  # ←—— Replace these two with your real values ———>
  NEXT_PUBLIC_SUPABASE_URL = "https://zrmhkcfdbyeubgyydfqr.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_WowIqy5-TByekVZ8lYkmuQ_JKrUHUKp"

[[plugins]]
  package = "@netlify/plugin-nextjs"
